application: hitheshcloud
version: 8
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /inc
  static_dir: inc
  
- url: /upload
  script: upload.php
  
- url: /
  script: upload.php
  
- url: /query
  script: query.php
  
